[workspace]
members = [
	"asset-registry",
	"auction",
	"authority",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/runtime-api",
	"tokens",
	"tokens/runtime-api",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"payments",
	"parameters",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"
