[workspace]
members = [
	"auction",
	"authority",
	"bencher",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/rpc",
	"oracle/rpc/runtime-api",
	"tokens",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"weight-gen",
	"weight-meter",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/paritytech/substrate']
frame-benchmarking = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
frame-support = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
frame-system = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-authority-discovery = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-authorship = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-babe = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-balances = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-elections-phragmen = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-scheduler = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-session = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-staking = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-timestamp = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-treasury = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
pallet-vesting = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sc-client-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sc-client-db = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sc-executor = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sc-executor-common = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sc-executor-wasmi = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sc-utils = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-application-crypto = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-arithmetic = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-authority-discovery = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-authorship = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-blockchain = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-consensus = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-core = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-debug-derive = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-externalities = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-inherents = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-io = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-keystore = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-npos-elections = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-panic-handler = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-runtime = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-runtime-interface = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-session = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-staking = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-state-machine = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-std = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-storage = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-tasks = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-timestamp = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-trie = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-version = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }
sp-wasm-interface = { git = "https://github.com/mangata-finance//substrate", branch = "feature/migration-0.9.16" }

[patch.'https://github.com/paritytech/cumulus']
cumulus-primitives-core = { git = "https://github.com/mangata-finance//cumulus", branch = "feature/v0.9.16-alignemnt" }
parachain-info = { git = "https://github.com/mangata-finance//cumulus", branch = "feature/v0.9.16-alignemnt" }
cumulus-pallet-dmp-queue = { git = "https://github.com/mangata-finance//cumulus", branch = "feature/v0.9.16-alignemnt" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/mangata-finance//cumulus", branch = "feature/v0.9.16-alignemnt" }
cumulus-pallet-xcm = { git = "https://github.com/mangata-finance//cumulus", branch = "feature/v0.9.16-alignemnt" }
#
# [patch.'https://github.com/paritytech/polkadot']
# xcm = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# xcm-executor = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# xcm-builder = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# pallet-xcm = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# polkadot-core-primitives = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# polkadot-runtime-parachains = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# polkadot-parachain = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# polkadot-primitives = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
# xcm-simulator = { git = "https://github.com/mangata-finance//polkadot", branch = "v0.9.16" }
