[workspace]
members = [
	"asset-registry",
	"auction",
	"authority",
	"bencher",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/rpc",
	"oracle/rpc/runtime-api",
	"tokens",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"weight-gen",
	"weight-meter",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/paritytech/substrate']
frame-benchmarking = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
frame-support = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
frame-system = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-authority-discovery = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-authorship = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-babe = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-balances = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-elections-phragmen = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-scheduler = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-session = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-staking = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-timestamp = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-treasury = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-vesting = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
pallet-transaction-payment = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sc-client-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sc-client-db = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sc-executor = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sc-executor-common = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sc-executor-wasmi = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sc-utils = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-application-crypto = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-arithmetic = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-authority-discovery = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-authorship = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-blockchain = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-consensus = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-consensus-slots = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-core = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-debug-derive = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-externalities = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-inherents = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-io = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-keystore = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-npos-elections = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-panic-handler = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-runtime = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-runtime-interface = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-session = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-staking = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-state-machine = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-std = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-storage = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-tasks = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-timestamp = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-trie = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-version = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-wasm-interface = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-tracing = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-maybe-compressed-blob = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }

#[patch.'https://github.com/paritytech/cumulus']
#cumulus-primitives-core = { git = "https://github.com/mangata-finance//cumulus", branch = "mangata-dev-v0.9.24" }
#parachain-info = { git = "https://github.com/mangata-finance//cumulus", branch = "mangata-dev-v0.9.24" }
#cumulus-pallet-dmp-queue = { git = "https://github.com/mangata-finance//cumulus", branch = "mangata-dev-v0.9.24" }
#cumulus-pallet-xcmp-queue = { git = "https://github.com/mangata-finance//cumulus", branch = "mangata-dev-v0.9.24" }
#cumulus-pallet-xcm = { git = "https://github.com/mangata-finance//cumulus", branch = "mangata-dev-v0.9.24" }

[patch.'https://github.com/paritytech/polkadot']
xcm = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
xcm-executor = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
xcm-builder = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
pallet-xcm = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
polkadot-core-primitives = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
polkadot-runtime-parachains = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
polkadot-parachain = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
polkadot-primitives = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
xcm-simulator = { git = "https://github.com/mangata-finance//polkadot", branch = "mangata-dev-v0.9.24" }
