[workspace]
members = [
	"auction",
	"authority",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"tokens",
	"traits",
	"utilities",
	"vesting",
	"rewards",
  "nft",
]

[patch."https://github.com/mangata-finance/open-runtime-module-library"]
orml-tokens = { path = "./tokens" }
orml-traits = { path = "./traits" }
