[package]
name = "orml-tokens"
description = "Fungible tokens module that implements `MultiCurrency` trait."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/tokens"
license = "Apache-2.0"
version = "0.4.1-dev"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.130", optional = true }
codec = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["max-encoded-len"] }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false }
sp-std = { path = "../../substrate/primitives/std", default-features = false }
frame-support = {  path = "../../substrate/frame/support", default-features = false }
frame-system = {  path = "../../substrate/frame/system", default-features = false }
orml-traits = { path = "../traits", version = "0.4.1-dev", default-features = false }
mangata-primitives = { path = "../../mangata-node/primitives/mangata", default-features = false, version = '0.1.0' }

[dev-dependencies]
sp-io = { path = "../../substrate/primitives/io" }
sp-core = { path = "../../substrate/primitives/core" }
pallet-treasury = { path = "../../substrate/frame/treasury" }
pallet-elections-phragmen = { path = "../../substrate/frame/elections-phragmen" }

# scale-info = { version = "1.0", default-features = false, features = ["derive"] }
# serde = { version = "1.0.130", optional = true }
# codec = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["max-encoded-len"] }
# sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
# sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
# frame-support = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
# frame-system = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
# orml-traits = { path = "../traits", version = "0.4.1-dev", default-features = false }
# mangata-primitives = { git="https://github.com/mangata-finance/substrate", branch="mangata-dev-v4", default-features = false, version = '0.1.0' }

# [dev-dependencies]
# sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
# sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
# pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
# pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"orml-traits/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
