on: [push]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install newset Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Install nightly-2022-11-11 with wasm
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-11
          target: wasm32-unknown-unknown
      - name: Check Cargo version
        run: |
          cargo --version
      - name: Use development Cargo.toml
        run: |
          cargo --version
          ln -s Cargo.dev.toml Cargo.toml
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          command: check
          args: -p orml-tokens -p orml-asset-registry
      - name: Test cargo check
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          command: test
          args: -p orml-tokens -p orml-asset-registry
